apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: infra-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/samatwa/goit-argo'
    path: monitoring
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: infra-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
